### ISSUE TITLE
Version information

### ISSUE THREAD

**Issue by lgmgeo** [SamuelNicaise/variantconvert#12]
Dear Sam,

Could you add version information in variantconvert?
In order to be able to run:
![image](https://user-images.githubusercontent.com/49909073/224268683-8e04afc3-20e9-4e49-a7ee-00bed08c80ea.png)
![image](https://user-images.githubusercontent.com/49909073/224268741-e6727109-5b6a-4ab7-9eff-0a5acc630985.png)

Many thanks,

Véronique

**Comment by SamuelNicaise** [comment]
Added in 0fa5024260fed0ccd28a1d1a5fa57f84a05bbbde 
I only added a --version flag, as -v is already used to set the verbosity level

If variantconvert was installed with pip, you can also use
> pip show version

**Comment by lgmgeo** [comment]
Perfect! Thanks!
