### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by lgmgeo** [SamuelNicaise/variantconvert#13]
Dear Sam,

When running variantconvert, there is no output display.
Would it be possible to display at least something minimalist like:
```
...running variantconvert version xxx
...Finished
``` 
if not desirable, you can close this issue.

Best,
Véronique

**Comment by SamuelNicaise** [comment]
Hi, 
Added in 35c846819a77ec229c34fa22582c3bbf334d9120 if verbose mode is info or debug
Best,

**Comment by lgmgeo** [comment]
Perfect! Thanks
