### ISSUE TITLE
anonymize module is not available

### ISSUE THREAD

**Issue by xiucz** [SamuelNicaise/variantconvert#9]
Hi , 
 I download the zip file from the GitHub,  then install by pip successfully. It gives the error. Which anonymize module should I install manually?

```
$ #download
$ unzip variantconvert-master.zip
$ conda create -n variantconvert
$ conda activate variantconvert
$ conda install pip
$ cd variantconvert
$ pip install -e .
$ variantconvert -h 
...
ModuleNotFoundError: No module named 'anonymize'
```
Best, 
xiucz

**Comment by SamuelNicaise** [comment]
Hi, this was fixed in 8535ba55ad451ae27db26b085f6367889b632d71 . The anonymize module is under development and should not have been in the master branch. 

Best,
